version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hbs_local
    volumes:
      - /tmp/postgresql-data:/var/lib/postgresql
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"